# Application name
spring.application.name=Student_Portal_Management

# DataSource configuration for MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/studentform
spring.datasource.username=root
spring.datasource.password=sql1506
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Enable SQL logging (for debugging SQL queries)
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
